name: Sample Run Max 2 Jobs In Parallel
on: 
  workflow_dispatch:
    inputs:    
      apps:
        description: 'JSON array of applications to deploy'
        required: true
        default: '[]'
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix: 
        run: ${{ fromJSON(github.event.inputs.apps) }}
    steps:
    - run: echo Run ${{ matrix.run }}
    - run: date
    - run: sleep 5 # Sleep so that we can see a difference in timestamp on the last run
    - run: date
